### ISSUE TITLE
JavaFX

### ISSUE THREAD

**Issue by hadim** [fiji/TrackMate3#30]
Do you consider switching to JavaFX at some point or not at all ?

I am asking because of a current project on which I won't have a lot of time to work on anytime soon : https://github.com/fiji/TrackMate/pull/89

So I could consider to develop it directly for the TM v3.

**Comment by tinevez** [comment]
No plan for JavaFX at the moment.

**Comment by tpietzsch** [comment]
@hadim I think it would be great if you could target TM3, too, although it might still be a little bit too early for it.

Ideally, it might be possible to make TrajEditor adaptable to both TM and TM3?

We plan for TM3 to have extension points for new Views using scijava annotations (similar to `@Plugin` for ImageJ2 plugins). The idea is that each View is operating on a `Graph` satisfying interfaces for specific `Vertex` and `Edge` with the properties that the View defines. The main TM3 model graph is then adapted to satisfy that interface, and the View operates on the wrapped model graph. We have listenable graphs etc so that Views can listen to changes to the (wrapped) model graph etc. The details are still subject to change, but should approach a stable design within the next few weeks.

**Comment by hadim** [comment]
Since I probably won't work on it before few weeks/months, I think I am going to target TM3 instead.

**Comment by tinevez** [comment]
Ok. Expect serious changes in the API anytime though.

**Comment by tinevez** [comment]
We discussed the JavaFX possibility with @tpietzsch and @fjug. 
None of us is experienced in JavaFX but at least one of us knows Swing. So we won't be going for JavaFX for this project and stick to swing.
